import type { SchemaData } from "@/types";

const schemaData: SchemaData = {
  title: "Eksempelskjema",
  subText: "Dette er et eksempelskjema som viser de ulike felttypene og funksjonene som kan konfigureres gjennom JSON data.",
  nextPageButton: {
    text: "Neste side",
  },
  previousPageButton: {
    text: "Forrige side",
  },
  submitButton: {
    text: "Send inn skjema",
    confirmation: {
      title: "Bekreft innsending",
      subText: "Er du sikker på at du vil sende inn skjemaet?",
      confirmButton: "Ja, send inn",
      cancelButton: "Avbryt",
    },
  },
  successMessage: "Ditt svar er registrert!",
  errorMessage: "En feil oppstod under innsending av skjemaet.",
  pages: [
    {
      name: "Side 1",
      title: "Side 1 - Enkle Felttyper og Grupperinger",
      subText: {
        spans: [{ text: "Denne siden inneholder eksempler på enkle felttyper, grupperte felter og deres diverse hjelpetekster." }],
      },
      fieldGroups: [
        {
          name: "Gruppe 1-1",
          title: "Grupperte Felter",
          subText: {
            text: "Felter som er gruppert sammen har mindre plass mellom seg.",
            helpText: "Dette kan overstyres med gapSize på gruppen.",
          },
        },
        {
          name: "Gruppe 1-2",
          title: "Sammenleggbar Gruppe",
          subText: "Denne gruppen kan foldes sammen for å spare plass.",
          collapsable: true,
        },
      ],
      fields: [
        {
          name: "tekstFelt1",
          label: "Tekstfelt",
          placeholder: "Skriv noe her...",
        },
        {
          name: "tekstFelt2",
          type: "text",
          noLabel: true,
          title: {
            text: "Tittel for tekstfelt",
            helpText: "Hjelpetekst for tittelen",
          },
          subText: {
            text: "Dette er en undertekst for tekstfeltet.",
            helpText: "Hjelpetekst for undertekst",
          },
          placeholder: "Skriv noe annet her...",
          description: "Beskrivelse for tekstfeltet.",
        },
        {
          name: "gruppe1Felt1",
          type: "text",
          label: "Tekstfelt 1 i en gruppe",
          groupName: "Gruppe 1-1",
        },
        {
          name: "gruppe1Felt2",
          type: "text",
          label: "Tekstfelt 2 i en gruppe",
          groupName: "Gruppe 1-1",
        },
        {
          name: "gruppe1Felt3",
          type: "text",
          label: "Tekstfelt 3 i en gruppe",
          groupName: "Gruppe 1-1",
        },
        {
          name: "gruppe2Felt1",
          type: "text",
          label: "Tekstfelt 1 i sammenleggbar gruppe",
          groupName: "Gruppe 1-2",
        },
        {
          name: "gruppe2Felt2",
          type: "text",
          label: "Tekstfelt 2 i sammenleggbar gruppe",
          groupName: "Gruppe 1-2",
        },
        {
          name: "tallFelt1",
          type: "number",
          label: "Tallfelt",
          placeholder: "Skriv et tall...",
        },
        {
          name: "kommentarFelt1",
          type: "comment",
          title: "Kommentar",
          noLabel: true,
          placeholder: "Skriv en kommentar...",
        },
      ],
    },
    {
      name: "Side 2",
      fieldGroups: [
        {
          name: "Gruppe 2-1",
          title: "Select varianter",
          subText: "Denne gruppen inneholder ulike varianter av select-felter.",
          gapSize: "half",
        },
      ],
      fields: [
        {
          name: "sjekkBoks1",
          type: "checkbox",
          label: "Sjekkboks",
          groupName: "Gruppe 2-1",
        },
        {
          name: "radioValg1",
          type: "radio",
          title: "Radioknapper",
          description: "Velg et alternativ",
          options: [
            { value: "valg1", label: "Valg 1" },
            { value: "valg2", label: "Valg 2" },
            { value: "valg3", label: "Valg 3" },
          ],
          groupName: "Gruppe 2-1",
        },
        {
          name: "multiSjekkBoks1",
          type: "multiCheckbox",
          title: "Flervalgssjekkbokser",
          description: "Velg en eller flere alternativer",
          options: [
            { value: "valg1", label: "Valg 1" },
            { value: "valg2", label: "Valg 2" },
            { value: "valg3", label: "Valg 3" },
          ],
          groupName: "Gruppe 2-1",
        },
        {
          name: "nedtrekksFelt1",
          type: "select",
          title: "Nedtrekksmeny",
          placeholder: "- Velg et alternativ -",
          options: [
            { value: "valg1", label: "Valg 1" },
            { value: "valg2", label: "Valg 2" },
            { value: "valg3", label: "Valg 3" },
          ],
          groupName: "Gruppe 2-1",
        },
        {
          name: "autofillFelt1",
          type: "autofill",
          title: "Autofill",
          description: "Dette feltet vil autofylle med alternativer basert på det du skriver.",
          placeholder: "Begynn å skrive...",
          required: true,
          requiredErrorText: "Dette feltet er obligatorisk.",
          options: [
            { value: "alpha", label: "Alpha" },
            { value: "beta", label: "Beta" },
            { value: "gamma", label: "Gamma" },
            { value: "delta", label: "Delta" },
            { value: "epsilon", label: "Epsilon" },
            { value: "zeta", label: "Zeta" },
            { value: "eta", label: "Eta" },
            { value: "theta", label: "Theta" },
            { value: "iota", label: "Iota" },
            { value: "kappa", label: "Kappa" },
            { value: "lambda", label: "Lambda" },
            { value: "mu", label: "Mu" },
            { value: "nu", label: "Nu" },
            { value: "xi", label: "Xi" },
            { value: "omicron", label: "Omicron" },
            { value: "pi", label: "Pi" },
            { value: "rho", label: "Rho" },
            { value: "sigma", label: "Sigma" },
            { value: "tau", label: "Tau" },
            { value: "upsilon", label: "Upsilon" },
            { value: "phi", label: "Phi" },
            { value: "chi", label: "Chi" },
            { value: "psi", label: "Psi" },
            { value: "omega", label: "Omega" },
          ],
          groupName: "Gruppe 2-1",
        },
      ],
    },
    {
      name: "Side 3",
      title: "Side 3 - Validering og Avhengigheter",
      subText: "Denne siden inneholder eksempler på felttyper med validering og avhengigheter.",
      fieldGroups: [
        {
          name: "Gruppe 3-1",
          title: "Validering og Avhengigheter",
          subText: "Denne gruppen inneholder felter som er avhengige av andre felter.",
          collapsable: true,
        },
        {
          name: "Gruppe 3-2",
          title: "Checkbokser med validering",
          collapsable: true,
        },
      ],
      fields: [
        {
          name: "ObligatoriskTekstFelt1",
          type: "text",
          label: "Obligatorisk Tekstfelt",
          placeholder: "Fyll inn noe her...",
          required: true,
          requiredErrorText: "Dette feltet er obligatorisk.",
        },
        {
          name: "epostFelt1",
          type: "text",
          label: "E-postadresse",
          placeholder: "Skriv inn noe som ligner en e-postadresse...",
          required: true,
          requiredErrorText: "Dette feltet er obligatorisk.",
          validationConditions: {
            regex: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
            regexErrorText: "Vennligst skriv inn en gyldig e-postadresse.",
          },
        },
        {
          name: "checkboks3",
          type: "checkbox",
          label: "Checkboks som må være blank",
          description: "Denne checkboksen må være blank for at skjemaet skal være gyldig.",
          required: true,
          requiredErrorText: "Denne checkboksen kan ikke være avkrysset.",
          validationConditions: {
            reverse: true,
          },
        },
        {
          name: "visAvhengig1",
          type: "checkbox",
          label: "Felt som kreves for å få tilgang til et annet felt",
          description: "Merk av for å vise det avhengige feltet.",
          required: true,
          requiredErrorText: "Dette feltet er obligatorisk.",
        },
        {
          name: "avhengigTekstFelt1",
          type: "text",
          label: "Avhengig Tekstfelt",
          placeholder: "Skriv noe her...",
          dependencies: [
            {
              dependsOn: "visAvhengig1",
            },
          ],
        },
        {
          name: "valideringFelt1",
          type: "text",
          label: "Tekst på mellom 5 og 10 tegn",
          description: "Dette feltet må ha mellom 5 og 10 tegn for å være gyldig.",
          required: true,
          requiredErrorText: "Dette feltet er obligatorisk.",
          validationConditions: {
            minValue: 5,
            minLengthErrorText: "Minimum lengde er 5 tegn.",
            maxValue: 10,
            maxLengthErrorText: "Maksimum lengde er 10 tegn.",
          },
        },
        {
          name: "multiSjekkBoks2",
          type: "multiCheckbox",
          label: "Velg minst ett alternativ",
          description: "Velg en eller flere alternativer, minst ett må velges.",
          required: true,
          requiredErrorText: "Du må velge minst ett alternativ.",
          options: [
            { value: "valg1", label: "Valg 1" },
            { value: "valg2", label: "Valg 2" },
            { value: "valg3", label: "Valg 3" },
            { value: "valg4", label: "Valg 4" },
          ],
          validationConditions: {
            minValue: 1,
            minLengthErrorText: "Du må velge minst ett alternativ.",
          },
        },
        {
          name: "multiSjekkBoks3",
          type: "multiCheckbox",
          label: "Velg 2 alternativer",
          description: "Du må velge nøyaktig to alternativer.",
          required: true,
          requiredErrorText: "Du må velge to alternativer.",
          options: [
            { value: "valg1", label: "Valg 1" },
            { value: "valg2", label: "Valg 2" },
            { value: "valg3", label: "Valg 3" },
            { value: "valg4", label: "Valg 4" },
          ],
          validationConditions: {
            minValue: 2,
            maxValue: 2,
            minLengthErrorText: "Du må velge to alternativer.",
            maxLengthErrorText: "Du må velge to alternativer.",
          },
        },
      ],
    },
    {
      name: "Side 4",
      title: "Side 4 - Stilsettinger og Tilpasning",
      subText: "Denne siden viser hvordan du kan tilpasse utseendet og stilen på feltene.",
      fieldGroups: [
        {
          name: "Gruppe 4-1",
          title: "Stilsetting og Tilpasning",
          subText: "Denne gruppen inneholder felter med tilpasset stil og utseende.",
          gapSize: "wide",
          tailwindClasses: "bg-gray-100 p-4 rounded-lg shadow-md",
        },
      ],
      fields: [
        {
          name: "stilTekstFelt1",
          type: "text",
          label: "Stilsettet Tekstfelt",
          placeholder: "Skriv noe her...",
          tailwindClasses: "text-blue-600 focus:ring-blue-500",
          description: "Dette tekstfeltet har tilpasset stil.",
        },
        {
          name: "stilSjekkBoks1",
          type: "checkbox",
          label: "Stilsettet Sjekkboks",
          description: "Denne sjekkboksen har tilpasset stil.",
          tailwindClasses: "text-blue-600 focus:ring-blue-500",
        },
        {
          name: "stilNedtrekksFelt1",
          type: "select",
          title: "Stilsettet Nedtrekksmeny",
          placeholder: "Velg et alternativ...",
          options: [
            { value: "valg1", label: "Valg 1" },
            { value: "valg2", label: "Valg 2" },
            { value: "valg3", label: "Valg 3" },
          ],
          tailwindClasses: "bg-blue-200 p-20",
          description: "Denne nedtrekksmenyen har tilpasset stil.",
        },
        {
          name: "stilAutofillFelt1",
          type: "autofill",
          title: "Stilsettet Autofill",
          description: "Dette autofill-feltet har tilpasset stil.",
          placeholder: "Begynn å skrive...",
          tailwindClasses: "bg-blue-200 p-20",
          required: true,
          requiredErrorText: "Dette feltet er obligatorisk.",
          options: [
            { value: "alpha", label: "Alpha" },
            { value: "beta", label: "Beta" },
            { value: "gamma", label: "Gamma" },
            { value: "delta", label: "Delta" },
            { value: "epsilon", label: "Epsilon" },
            { value: "zeta", label: "Zeta" },
            { value: "eta", label: "Eta" },
            { value: "theta", label: "Theta" },
            { value: "iota", label: "Iota" },
            { value: "kappa", label: "Kappa" },
            { value: "lambda", label: "Lambda" },
            { value: "mu", label: "Mu" },
            { value: "nu", label: "Nu" },
            { value: "xi", label: "Xi" },
            { value: "omicron", label: "Omicron" },
            { value: "pi", label: "Pi" },
            { value: "rho", label: "Rho" },
            { value: "sigma", label: "Sigma" },
            { value: "tau", label: "Tau" },
            { value: "upsilon", label: "Upsilon" },
            { value: "phi", label: "Phi" },
            { value: "chi", label: "Chi" },
            { value: "psi", label: "Psi" },
            { value: "omega", label: "Omega" },
          ],
        },
      ],
    },
  ],
};

export default schemaData;
